live_config_reload=true

[font]
normal = { family = 'Hack', style = 'Regular' }
size = 10.5
offset = { x = 0, y = 1 }

[window]
opacity = 0.8
padding = { x = 2, y = 2 }
decorations = 'None'

[bell]
animation = 'EaseOutQuad'
color = '#444444'
duration = 0

[cursor]
style = { shape = 'Block', blinking = 'Always' }
unfocused_hollow = true
blink_timeout = 0

[colors.cursor]
cursor = '#f57f1f'

[colors.primary]
background= '#101216'
foreground= '#d3dae3'

[colors.normal]
black=   '#4b5164'
red=     '#e14245'
green=   '#5ca75b'
yellow=  '#f6ab32'
blue=    '#4877b1'
magenta= '#a660c3'
cyan=    '#5294e2'
white=   '#a9a9aa'

[colors.dim]
black=   '#616981'
red=     '#e16f7e'
green=   '#add488'
yellow=  '#fdc35f'
blue=    '#8ca9bf'
magenta= '#e2afec'
cyan=    '#73c5e2'
white=   '#fcfcfc'

[colors.bright]
black=   '#616981'
red=     '#e16f7e'
green=   '#add488'
yellow=  '#fdc35f'
blue=    '#8ca9bf'
magenta= '#e2afec'
cyan=    '#73c5e2'
white=   '#fcfcfc'

